# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Shifts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shifts
  pod 'RIBs'
  pod 'SwiftGen'
  pod 'When'

  target 'ShiftsTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod 'Sourcery'
    
  end
end
